import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'
import CatalogComponent from '../components/Catalog'

const Nav = dynamic(() => import('main/nav'), {ssr: false})
const Footer = dynamic(() => import('main/footer'), {ssr: false})
const inter = Inter({ subsets: ['latin'] })

export default function Catalog() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Nav>Navbar in shop-app 3001</Nav>
        Welcome to Catalog port:3001
        the more change!!
        <CatalogComponent />
        <Footer />
      </main>
    </>
  )
}
